### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Pakeetharan** [sumeshpremraj/saavn-dl#2]
Tried both git clone and pip3 install

[Issue Here](http://i.imgur.com/1398TtN.png)

**Comment by sumeshpremraj** [comment]
This was caused by hard coded log file path, fixed in commit 3c55afa63de05528552f53a2625c11272676be0c

**Comment by Pakeetharan** [comment]
Ohh Thanks
Waiting for the Windows release 👍
