### ISSUE TITLE
error at line 43 and 59

### ISSUE THREAD

**Issue by SJ50** [sumeshpremraj/saavn-dl#3]
I trying to run this in ubuntu.
at line 43 Missing parentheses
at line 59
File "saavn-dl", line 59, in <module>
    con.execute('CREATE TABLE IF NOT EXISTS saavn_' + playlist_name + '''(
NameError: name 'con' is not defined

I do not know python otherwise I have added PR.

**Comment by sumeshpremraj** [comment]
@SJ50 are you running this on python3?

**Comment by SJ50** [comment]
yes I used python3
